spring:
  application:
    name: ecom-assistant

  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eas}
    username: ${SPRING_DATASOURCE_USERNAME:eas}
    password: ${SPRING_DATASOURCE_PASSWORD:eas}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Connection Pool Configuration
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # AI Configuration
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-3-small
      api-key: ${OPEN_AI_TOKEN}
      chat:
        options:
          model: gpt-4o-mini
#    ollama:
#      chat:
#        options:
#          model: qwen3:latest


# Application Configuration
logging:
  level:
    org:
      hibernate:
        SQL: WARN
      springframework:
        ai: DEBUG
    com:
      ecomassistant: DEBUG